# action.yml
name: 'Saxon'
description: 'Runs Saxon-HE'
inputs:
  args:
    description: 'Arguments to pass to the Saxon-HE command'
    required: false
runs:
  using: 'composite'
  steps:
    - id: github
      uses: pl-strflt/docker-container-action/.github/actions/github@v1
    - uses: pl-strflt/docker-container-action@v1
      with:
        repository: ${{ steps.github.outputs.action_repository }}
        ref: ${{ steps.github.outputs.action_ref }}
        args: ${{ inputs.args }}
